openapi: 3.0.0
info:
  title: Card Switches API
  version: 1.0.0
paths:
  /cards/switches:
    post:
      summary: Update card switches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cardNumber:
                  type: string
                switchType:
                  type: string
                enabled:
                  type: boolean
              required:
                - cardNumber
                - switchType
                - enabled
      responses:
        '200':
          description: Switches updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string 