openapi: 3.0.0
info:
  title: Credit Card API
  version: 1.0.0
paths:
  /creditcards:
    get:
      summary: List credit cards for a customer
      parameters:
        - in: query
          name: customerId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Credit card list
          content:
            application/json:
              schema:
                type: object
                properties:
                  cards:
                    type: array
                    items:
                      type: object
                      properties:
                        cardNumber:
                          type: string
                        cardType:
                          type: string 