openapi: 3.0.0
info:
  title: Loyalty Cards API
  version: 1.0.0
paths:
  /loyalty/cards:
    get:
      summary: List loyalty cards for a user
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Loyalty cards
          content:
            application/json:
              schema:
                type: object
                properties:
                  cards:
                    type: array
                    items:
                      type: object
                      properties:
                        cardNumber:
                          type: string
                        program:
                          type: string 