openapi: 3.0.0
info:
  title: Credit Card List API
  version: 1.0.0
paths:
  /cards/list:
    post:
      summary: Get list of credit cards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
              required:
                - customerId
      responses:
        '200':
          description: List of credit cards
          content:
            application/json:
              schema:
                type: object
                properties:
                  cards:
                    type: array
                    items:
                      type: object
                      properties:
                        cardNumber:
                          type: string
                        cardType:
                          type: string
                        expiryDate:
                          type: string 