openapi: 3.0.0
info:
  title: Payment Service API
  version: 1.0.0
paths:
  /payments:
    post:
      summary: Submit a payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fromAccount:
                  type: string
                toAccount:
                  type: string
                amount:
                  type: number
              required:
                - fromAccount
                - toAccount
                - amount
      responses:
        '200':
          description: Payment response
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                  status:
                    type: string 