openapi: 3.0.0
info:
  title: Payments API
  version: 1.0.0
paths:
  /payments/transfer:
    post:
      summary: Transfer funds between accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fromAccountId:
                  type: string
                toAccountId:
                  type: string
                amount:
                  type: number
              required:
                - fromAccountId
                - toAccountId
                - amount
      responses:
        '200':
          description: Payment transfer response
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                  status:
                    type: string
                  message:
                    type: string 