openapi: 3.0.0
info:
  title: Transaction API
  version: 1.0.0
paths:
  /transactions:
    get:
      summary: Get transactions for an account
      parameters:
        - in: query
          name: accountId
          schema:
            type: string
          required: true
        - in: query
          name: from
          schema:
            type: string
        - in: query
          name: to
          schema:
            type: string
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        transactionId:
                          type: string
                        date:
                          type: string
                        amount:
                          type: number 