openapi: 3.0.0
info:
  title: Statement API
  version: 1.0.0
paths:
  /statement:
    get:
      summary: Get account statement
      parameters:
        - in: query
          name: account
          schema:
            type: string
          required: true
        - in: query
          name: period
          schema:
            type: string
      responses:
        '200':
          description: Account statement
          content:
            application/json:
              schema:
                type: object
                properties:
                  statementId:
                    type: string
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        entryId:
                          type: string
                        date:
                          type: string 